version: '3'

services:

  nats-server:
    image: nats:latest

  client-gateway:
    build: 
      context: ./client-gateway
      dockerfile: Dockerfile.prod
    image: us-east1-docker.pkg.dev/microservices-426101/image-registry/client-gateway-prod
    ports:
      - "${CLIENT_GATEWAY_PORT}:${CLIENT_GATEWAY_PORT}"
    environment:
      - PORT=3000
      - NATS_SERVERS=nats://nats-server:${NATS_SERVER_PORT}
      - DATABASE_URL=${AUTH_DATABASE_URL}

  products-ms:
    build: 
      context: ./products-ms
      dockerfile: Dockerfile.prod
    image: us-east1-docker.pkg.dev/microservices-426101/image-registry/products-ms-prod
    environment:
      - PORT=${INTERNAL_PORT}
      - NATS_SERVERS=nats://nats-server:${NATS_SERVER_PORT}
      - DATABASE_URL=file:./dev.db
    depends_on:
      - nats-server

# =======================
# Payments Microservice
# =======================
  payments-ms:
    build: 
      context: ./payments-ms
      dockerfile: Dockerfile.prod
    image: us-east1-docker.pkg.dev/microservices-426101/image-registry/payments-ms-prod
    ports:
      - ${PAYMENTS_MS_PORT}:${PAYMENTS_MS_PORT}
    environment:
      - PORT=${PAYMENTS_MS_PORT}
      - NATS_SERVERS=nats://nats-server:${NATS_SERVER_PORT}
      - STRIPE_API_KEY=${STRIPE_API_KEY}
      - STRIPE_ENDPOINT_SECRET=${STRIPE_ENDPOINT_SECRET}
      - STRIPE_SUCCESS_URL=${STRIPE_SUCCESS_URL}
      - STRIPE_CANCEL_URL=${STRIPE_CANCEL_URL}
    depends_on:
      - nats-server

# =======================
# Auth Microservice
# =======================
  auth-ms:
    build: 
      context: ./auth-ms
      dockerfile: Dockerfile.prod
    image: us-east1-docker.pkg.dev/microservices-426101/image-registry/auth-ms-prod
    environment:
      - PORT=${INTERNAL_PORT}
      - NATS_SERVERS=//nats-server:${NATS_SERVER_PORT}
      - DATABASE_URL=${AUTH_DATABASE_URL}
      - JWT_SECRET=${JWT_SECRET}
    depends_on:
      - nats-server

  orders-ms:
    build: 
      context: ./orders-ms
      dockerfile: Dockerfile.prod
      args:
        - ORDERS_DATABASE_URL=${ORDERS_DATABASE_URL}
    image: us-east1-docker.pkg.dev/microservices-426101/image-registry/order-ms-prod
    environment:
      - PORT=${INTERNAL_PORT}
      - NATS_SERVERS=nats://nats-server:${NATS_SERVER_PORT}
      - DATABASE_URL=${ORDERS_DATABASE_URL}
    depends_on:
      - nats-server