apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: payments-ms-prod
  name: payments-ms-prod
spec:
  replicas: 1
  selector:
    matchLabels:
      app: payments-ms-prod
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: payments-ms-prod
    spec:
      containers:
      - image: us-east1-docker.pkg.dev/microservices-426101/image-registry/payments-ms-prod
        name: payments-ms-prod
        env:
          - name: PORT
            value: "3000"
          - name: NATS_SERVERS
            value: "nats://nats"
          - name: STRIPE_SUCCESS_URL
            value: "http://localhost:3003/payments/success"
          - name: STRIPE_CANCEL_URL
            value: "http://localhost:3003/payments/cancel"
          - name: STRIPE_API_KEY
            valueFrom:
              secretKeyRef:
                name: payments-secrets
                key: stripe_api_key
          - name: STRIPE_ENDPOINT_SECRET
            valueFrom:
              secretKeyRef:
                name: payments-secrets
                key: stripe_endpoint_secret
        resources: {}
status: {}
